---
- hosts: develop_machine
  become: yes
  vars:
    NODEJS_VERSION: "8"
    DISTRO: "xenial" #trusty
  tasks:

  - name: Install gpg key for nodejs LTS
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
    
  - name: Install the nodejs LTS repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ DISTRO }} main"
      state: present
      update_cache: yes

  - name: Install nodejs
    apt: 
      name: nodejs
      state: present

  - name: Manually change npm’s default directory
    become_user: rafael
    become: yes
    shell: |
      mkdir ~/.npm-global
      npm config set prefix '~/.npm-global'
      export PATH=~/.npm-global/bin:$PATH
      source ~/.profile
  
