---
- hosts: develop_machine
  become: yes
  vars:
    NODEJS_VERSION: "8"
    DISTRO: "xenial" #trusty
  tasks:

  - name: Install gpg key for nodejs LTS
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
    
  - name: Install the nodejs LTS repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ DISTRO }} main"
      state: present
      update_cache: yes

  - name: Install nodejs
    apt: nodejs
    state: present